name: Run tests on PR

on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
  push:
  workflow_dispatch:

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 19.x

      - name: Log Node version
        run: node --version

      - name: Log NPM version
        run: npm --version

      - name: Set up npm cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-${{ hashFiles('package-lock.json') }}
            ${{ runner.OS }}

      - name: Install npm dependencies
        run: npm ci

      - name: Build locales
        run: node scripts/build-locales

      - name: Build code
        run: NODE_ENV=production npm run build

      - name: Run tests
        run: npm run test-ci

      - name: Smoke test
        run: npm run smoke-test-eslint-version-conflicts
